### ISSUE TITLE
Assert in WebKit::ThreadedCompositor::frameComplete

### ISSUE THREAD

**Issue by vertexodessa** [WebPlatformForEmbedded/WPEWebKit#156]
```
Core was generated by `/usr/bin/WPEWebProcess 36 -1'.
Program terminated with signal SIGBUS, Bus error.
#0  0x755084f8 in WTFCrash () at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/Assertions.cpp:324
324         *(int *)(uintptr_t)0xbbadbeef = 0;
(gdb) bt
#0  0x755084f8 in WTFCrash () at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/Assertions.cpp:324
#1  0x737506d4 in WebKit::ThreadedCompositor::frameComplete (this=0x6e5fa230)
    at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebKit2/Shared/CoordinatedGraphics/threadedcompositor/ThreadedCompositor.cpp:323
#2  0x748b2eec in WebCore::PlatformDisplayWPE::EGLTarget::EGLTarget(WebCore::PlatformDisplayWPE const&, WebCore::PlatformDisplayWPE::EGLTarget::Client&, int)::{lambda(void*)#1}::_FUN(void*) ()
    at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebCore/platform/graphics/wpe/PlatformDisplayWPE.cpp:93
#3  0x71592f00 in wpe_renderer_backend_egl_target_dispatch_frame_complete (target=<optimized out>)
    at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/ThirdParty/WPE/src/renderer-backend-egl.c:183
#4  0x6e6b710c in operator() (__closure=0x0, callback=<optimized out>, data=0x5a5028c8)
    at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/ThirdParty/WPE-platform/src/westeros/renderer-backend.cpp:229
#5  Westeros::EGLTarget::<lambda(void*, wl_callback*, uint32_t)>::_FUN(void *, wl_callback *, uint32_t) ()
    at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/ThirdParty/WPE-platform/src/westeros/renderer-backend.cpp:230
#6  0x72305b9c in noretval () at /usr/src/debug/libffi/3.0.13-r0/libffi-3.0.13/src/mips/o32.S:172
#7  0x723056c8 in ffi_call (cif=<optimized out>, fn=<optimized out>, rvalue=<optimized out>, avalue=<optimized out>) at /usr/src/debug/libffi/3.0.13-r0/libffi-3.0.13/src/mips/ffi.c:605
#8  0x77deb218 in wl_closure_invoke (closure=<optimized out>, flags=<optimized out>, target=0x5a50d238, opcode=0, data=0x5a5028c8) at /usr/src/debug/wayland/1.6.0-r0/wayland-1.6.0/src/connection.c:934
#9  0x77de7680 in dispatch_event (display=0x441240, queue=<optimized out>) at /usr/src/debug/wayland/1.6.0-r0/wayland-1.6.0/src/wayland-client.c:1136
#10 0x77de7740 in dispatch_queue (display=0x441240, queue=0x4412a8) at /usr/src/debug/wayland/1.6.0-r0/wayland-1.6.0/src/wayland-client.c:1261
#11 0x77de8994 in wl_display_dispatch_queue (display=0x441240, queue=0x4412a8) at /usr/src/debug/wayland/1.6.0-r0/wayland-1.6.0/src/wayland-client.c:1445
#12 0x77de8b34 in wl_display_dispatch (display=<optimized out>) at /usr/src/debug/wayland/1.6.0-r0/wayland-1.6.0/src/wayland-client.c:1512
#13 0x6e6b7098 in operator() (__closure=0x0, base=0x445458)
    at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/ThirdParty/WPE-platform/src/westeros/renderer-backend.cpp:72
#14 Westeros::EventSource::<lambda(GSource*, GSourceFunc, gpointer)>::_FUN(GSource *, GSourceFunc, gpointer) ()
    at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/ThirdParty/WPE-platform/src/westeros/renderer-backend.cpp:79
#15 0x71867bc8 in g_main_dispatch (context=0x439798) at /usr/src/debug/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:3154
#16 g_main_context_dispatch (context=0x439798) at /usr/src/debug/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:3769
#17 0x71867ef4 in g_main_context_iterate (context=0x439798, block=1, dispatch=1, self=<optimized out>) at /usr/src/debug/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:3840
#18 0x71868554 in g_main_loop_run (loop=0x439838) at /usr/src/debug/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:4034
#19 0x75558994 in WTF::RunLoop::run () at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:97
#20 0x73790100 in WebKit::ChildProcessMain<WebKit::WebProcess, WebKit::WebProcessMain> (argc=3, argv=0x7fd9e944)
    at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebKit2/Shared/unix/ChildProcessMain.h:61
#21 0x7378fc5c in WebKit::WebProcessMainUnix (argc=<optimized out>, argv=<optimized out>)
    at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebKit2/WebProcess/wpe/WebProcessMainWPE.cpp:81
#22 0x00404fdc in main (argc=3, argv=0x7fd9e944) at /mnt/cached/Yocto/WPE/build-pacexg1v3/tmp/work/mips32el-rdk-linux/wpe-webkit/0.1+gitAUTOINC+528200a31f-r0/git/Source/WebKit2/WebProcess/EntryPoint/unix/WebProcessMain.cpp:52

```

**Comment by albertd** [comment]
@vertexodessa please reopen if reproducible in wpe-2017 branch
