### ISSUE TITLE
unload or destroy media player after WPE process exit

### ISSUE THREAD

**Issue by vbojja001c** [WebPlatformForEmbedded/WPEWebKit#353]
When I open and play some content in YouTube, I see the load() is called to instantiate and load a media player. And another load() would be called for every asset/content change within youtube. When doing another load() the previous media player is destructed. However on YouTube exit the media player is not destructed. Is there an unload or destroy equivalent method to destruct the player on YouTube exit?

**Comment by eocanha** [comment]
I don't think there's any method to explicitly destroy the private player. What I've seen in debugging sessions while exiting YouTube is that the old MediaPlayerPrivateGStreamerBase (superclass of all our player privates) is destroyed as part of a new HTMLMediaElement::createMediaPlayer() operation which replaces the old player (being destroyed) with a new one:

```
#0  0x76764930 in WebCore::MediaPlayerPrivateGStreamerBase::~MediaPlayerPrivateGStreamerBase() () from /home/enrique/buildroot-wpe/output/staging/usr/lib/libWPEWebKit.so.0
#1  0x76762db4 in WebCore::MediaPlayerPrivateGStreamer::~MediaPlayerPrivateGStreamer() () from /home/enrique/buildroot-wpe/output/staging/usr/lib/libWPEWebKit.so.0
#2  0x767710c2 in WebCore::MediaPlayerPrivateGStreamerMSE::~MediaPlayerPrivateGStreamerMSE() () from /home/enrique/buildroot-wpe/output/staging/usr/lib/libWPEWebKit.so.0
#3  0x76771200 in WebCore::MediaPlayerPrivateGStreamerMSE::~MediaPlayerPrivateGStreamerMSE() () from /home/enrique/buildroot-wpe/output/staging/usr/lib/libWPEWebKit.so.0
#4  0x765a6d7e in WebCore::MediaPlayer::~MediaPlayer() () from /home/enrique/buildroot-wpe/output/staging/usr/lib/libWPEWebKit.so.0
#5  0x765a6dcc in WebCore::MediaPlayer::~MediaPlayer() () from /home/enrique/buildroot-wpe/output/staging/usr/lib/libWPEWebKit.so.0
#6  0x7644a410 in WebCore::HTMLMediaElement::createMediaPlayer() () from /home/enrique/buildroot-wpe/output/staging/usr/lib/libWPEWebKit.so.0
#7  0x7644a948 in WebCore::HTMLMediaElement::prepareForLoad() () from /home/enrique/buildroot-wpe/output/staging/usr/lib/libWPEWebKit.so.0
#8  0x7644c7a2 in WebCore::HTMLMediaElement::load() () from /home/enrique/buildroot-wpe/output/staging/usr/lib/libWPEWebKit.so.0
#9  0x76a5a712 in WebCore::jsHTMLMediaElementPrototypeFunctionLoad(JSC::ExecState*) () from /home/enrique/buildroot-wpe/output/staging/usr/lib/libWPEWebKit.so.0
#10 0x6fd412c8 in ?? ()
```

This newly created MediaPlayer doesn't spawn any internal MediaPlayerPrivateGStreamerBase (or descendant). Instead, it keeps the default NullMediaPlayerPrivate, which doesn't keep any resources and shouldn't worry us.

I've added some traces in selected places to illustrate the previous explanation. This is the first load of a video which is later exited. You can see how the NullMediaPlayerPrivate remains:

```
### WebCore::NullMediaPlayerPrivate::NullMediaPlayerPrivate(WebCore::MediaPlayer*): 0x64e8ba98
### WebCore::MediaPlayer::MediaPlayer(WebCore::MediaPlayerClient&): 0x64fcccf0
### void WebCore::HTMLMediaElement::createMediaPlayer(): m_player = 0x64fcccf0
### WebCore::NullMediaPlayerPrivate::NullMediaPlayerPrivate(WebCore::MediaPlayer*): 0x64edd768
### WebCore::MediaPlayer::MediaPlayer(WebCore::MediaPlayerClient&): 0x64fcc678
### virtual WebCore::MediaPlayer::~MediaPlayer(): 0x64fcccf0
### virtual WebCore::NullMediaPlayerPrivate::~NullMediaPlayerPrivate(): 0x64e8ba98
### void WebCore::HTMLMediaElement::createMediaPlayer(): m_player = 0x64fcc678
### WebCore::NullMediaPlayerPrivate::NullMediaPlayerPrivate(WebCore::MediaPlayer*): 0x612dc8b0
### WebCore::MediaPlayer::MediaPlayer(WebCore::MediaPlayerClient&): 0x61301a10
### virtual WebCore::MediaPlayer::~MediaPlayer(): 0x64fcc678
### virtual WebCore::NullMediaPlayerPrivate::~NullMediaPlayerPrivate(): 0x64edd768
### void WebCore::HTMLMediaElement::createMediaPlayer(): m_player = 0x61301a10
### virtual WebCore::MediaPlayer::~MediaPlayer(): 0x61301a10
### virtual WebCore::NullMediaPlayerPrivate::~NullMediaPlayerPrivate(): 0x612dc8b0
### void WebCore::HTMLMediaElement::clearMediaPlayer(WebCore::HTMLMediaElementEnums::DelayedActionType): m_player = (nil)
### WebCore::NullMediaPlayerPrivate::NullMediaPlayerPrivate(WebCore::MediaPlayer*): 0x612dcb08
### WebCore::MediaPlayer::MediaPlayer(WebCore::MediaPlayerClient&): 0x61301b80
### void WebCore::HTMLMediaElement::createMediaPlayer(): m_player = 0x61301b80
### bool WebCore::MediaPlayer::load(const WebCore::URL&, const WebCore::ContentType&, WebCore::MediaSourcePrivateClient*)
### WebCore::MediaPlayerPrivateGStreamerBase::MediaPlayerPrivateGStreamerBase(WebCore::MediaPlayer*)
### WebCore::MediaPlayerPrivateGStreamerMSE::MediaPlayerPrivateGStreamerMSE(WebCore::MediaPlayer*)
### virtual WebCore::NullMediaPlayerPrivate::~NullMediaPlayerPrivate(): 0x612dcb08
### void WebCore::MediaPlayer::loadWithNextMediaEngine(const WebCore::MediaPlayerFactory*): m_private = 0x68cf0000
### void WebCore::MediaPlayer::loadWithNextMediaEngine(const WebCore::MediaPlayerFactory*): loading blob:https://www.youtube.com/8989a6bb-0352-46db-8b25-b811727d1e4e
### WebCore::NullMediaPlayerPrivate::NullMediaPlayerPrivate(WebCore::MediaPlayer*): 0x613403b0
### WebCore::MediaPlayer::MediaPlayer(WebCore::MediaPlayerClient&): 0x583fe228
### virtual WebCore::MediaPlayer::~MediaPlayer(): 0x61301b80
### virtual WebCore::MediaPlayerPrivateGStreamerMSE::~MediaPlayerPrivateGStreamerMSE()
### virtual WebCore::MediaPlayerPrivateGStreamerBase::~MediaPlayerPrivateGStreamerBase()
### void WebCore::HTMLMediaElement::createMediaPlayer(): m_player = 0x583fe228
```

**Comment by eocanha** [comment]
Anyway, how is the YouTube app destroyed in your specific platform? "politely" (pressing escape or back and going through the "Are you sure you want to exit YouTube" dialog) or in some other abrupt way?

**Comment by albertd** [comment]
This has been resolved within wpe-2017, even suspend mode releases the resources now
