### ISSUE TITLE
WebProcess crash in WebKit::CoordinatedBackingStoreTile::setBackBuffer

### ISSUE THREAD

**Issue by emutavchi** [WebPlatformForEmbedded/WPEWebKit#529]
Reproduced on wpe-20170728 at c699f32f92e227955b252528ed8ececa6118793e

Full backtrace is available here: https://gist.github.com/emutavchi/396fdae56a19ef9f9f95b4b08c713c0c

Crashed thread:

```
Core was generated by `/usr/bin/WPEWebProcess 32 -1'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x75bc2c1c in WebKit::CoordinatedBackingStoreTile::setBackBuffer(WebCore::IntRect const&, WebCore::IntRect const&, WTF::RefPtr<WebCore::CoordinatedSurface>&&, WebCore::IntPoint const&) (this=0x4, 
    tileRect=..., sourceRect=..., buffer=<unknown type in /home/imutavchi/Downloads/PX032ANI_VBN_1808_sprint_20180820221423sdy_amazon/usr/lib/.debug/libWPEWebKit.so.0.0.20170728, CU 0x8a21ffd, DIE 0x8a49bc3>, 
    offset=...)
    at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/CoordinatedGraphics/CoordinatedBackingStore.cpp:85
85          m_sourceRect = sourceRect;
(gdb) bt
#0  0x75bc2c1c in WebKit::CoordinatedBackingStoreTile::setBackBuffer(WebCore::IntRect const&, WebCore::IntRect const&, WTF::RefPtr<WebCore::CoordinatedSurface>&&, WebCore::IntPoint const&) (this=0x4, tileRect=..., sourceRect=..., buffer=<unknown type in /home/imutavchi/Downloads/PX032ANI_VBN_1808_sprint_20180820221423sdy_amazon/usr/lib/.debug/libWPEWebKit.so.0.0.20170728, CU 0x8a21ffd, DIE 0x8a49bc3>, offset=...) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/CoordinatedGraphics/CoordinatedBackingStore.cpp:85
#1  0x75bc3518 in WebKit::CoordinatedBackingStore::updateTile(unsigned int, WebCore::IntRect const&, WebCore::IntRect const&, WTF::RefPtr<WebCore::CoordinatedSurface>&&, WebCore::IntPoint const&) (this=<optimized out>, id=<optimized out>, sourceRect=..., tileRect=..., backBuffer=<unknown type in /home/imutavchi/Downloads/PX032ANI_VBN_1808_sprint_20180820221423sdy_amazon/usr/lib/.debug/libWPEWebKit.so.0.0.20170728, CU 0x8a21ffd, DIE 0x8a49bc3>, offset=...) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/CoordinatedGraphics/CoordinatedBackingStore.cpp:113
#2  0x75bc8e2c in WebKit::CoordinatedGraphicsScene::updateTilesIfNeeded (this=0x71a8f000, layer=<optimized out>, state=...) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/CoordinatedGraphics/CoordinatedGraphicsScene.cpp:434
#3  0x75bcba64 in WebKit::CoordinatedGraphicsScene::setLayerState (this=0x71a8f000, id=<optimized out>, layerState=...) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/CoordinatedGraphics/CoordinatedGraphicsScene.cpp:296
#4  0x75bcc4dc in WebKit::CoordinatedGraphicsScene::commitSceneState (this=0x71a8f000, state=...) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/CoordinatedGraphics/CoordinatedGraphicsScene.cpp:560
#5  0x75bcc59c in WebKit::CoordinatedGraphicsScene::applyStateChanges (this=0x71a8f000, states=...) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/CoordinatedGraphics/CoordinatedGraphicsScene.cpp:95
#6  0x75bd13b8 in WebKit::ThreadedCompositor::renderLayerTree (this=0x71af75b0) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/CoordinatedGraphics/threadedcompositor/ThreadedCompositor.cpp:292
#7  0x75bcd3bc in WTF::Function<void ()>::operator()() const (this=0x71afa4f0) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/Function.h:56
#8  WebKit::CompositingRunLoop::updateTimerFired (this=0x71afa4c8) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/CoordinatedGraphics/threadedcompositor/CompositingRunLoop.cpp:258
#9  0x77a594ec in WTF::RunLoop::TimerBase::<lambda(gpointer)>::operator() (__closure=0x0, userData=0x71afa4c8) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:166
#10 WTF::RunLoop::TimerBase::<lambda(gpointer)>::_FUN(gpointer) () at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:170
#11 0x74804f6c in g_main_dispatch (context=0x6f602a00) at /usr/src/debug/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:3154
#12 g_main_context_dispatch (context=0x6f602a00) at /usr/src/debug/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:3769
#13 0x748052c0 in g_main_context_iterate (context=0x6f602a00, block=1, dispatch=1, self=<optimized out>) at /usr/src/debug/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:3840
#14 0x748058e8 in g_main_loop_run (loop=0x6f6032c8) at /usr/src/debug/glib-2.0/1_2.48.1-r0/glib-2.48.1/glib/gmain.c:4034
#15 0x77a59cec in WTF::RunLoop::run () at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/glib/RunLoopGLib.cpp:96
#16 0x77a58028 in WTF::WorkQueue::<lambda()>::operator() (__closure=0x71afb55c) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/generic/WorkQueueGeneric.cpp:44
#17 WTF::Function<void()>::CallableWrapper<WTF::WorkQueue::platformInitialize(char const*, WTF::WorkQueue::Type, WTF::WorkQueue::QOS)::<lambda()> >::call(void) (this=0x71afb558) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/Function.h:101
#18 0x77a27fec in WTF::Function<void ()>::operator()() const (this=<synthetic pointer>) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/Function.h:56
#19 WTF::Thread::entryPoint (newThreadContext=0x71aab1e0) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/Threading.cpp:129
#20 0x77a563a8 in WTF::wtfThreadEntryPoint (context=<optimized out>) at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WTF/wtf/ThreadingPthreads.cpp:223
#21 0x7565eb6c in start_thread (arg=0x0) at pthread_create.c:314
#22 0x75378d10 in __thread_start () at ../ports/sysdeps/unix/sysv/linux/mips/clone.S:150
```

Note tiles map is empty:

```
(gdb) f 2
#2  0x75bc8e2c in WebKit::CoordinatedGraphicsScene::updateTilesIfNeeded (this=0x71a8f000, layer=<optimized out>, state=...)
    at /mnt/jenkins/workspace/PACEXI3V2-Yocto-Build/build-pacexi3v2/tmp/work/mips32el-rdk-linux/wpe-webkit/0.4+gitAUTOINC+c699f32f92-r0/git/Source/WebKit/Shared/CoordinatedGraphics/CoordinatedGraphicsScene.cpp:434
434             backingStore->updateTile(tile.tileID, surfaceUpdateInfo.updateRect, tile.tileRect, surfaceIt->value.copyRef(), surfaceUpdateInfo.surfaceOffset);
(gdb) p backingStore.m_ptr.m_tiles
$1 = {m_impl = {static m_maxLoad = 2, static m_minLoad = 6, m_table = 0x0, m_tableSize = 0, m_tableSizeMask = 0, m_keyCount = 0, m_deletedCount = 0}}
```

**Comment by albertd** [comment]
@emutavchi do you have a bit more info on which application is being used?

**Comment by emutavchi** [comment]
Hi Albert, sorry for slow response. This was on Amazon's MSE/EME long video playback test, running under low memory conditions triggering lots of rebuffering and showing video tag's UI a lot.

**Comment by magomez** [comment]
Ah, found it. It's a regression that happened upstream that got backported here, and then reverted upstream but not reverted here. I backported the revert as well. Let me test it a bit and I'll push it.

**Comment by magomez** [comment]
I've just pushed 5de31f2c34ab2768264c925e672f961d0223ba85 that should fix this.
